steps:
# Build the container image
- name: "gcr.io/cloud-builders/docker"
  args:
  - "build"
  - "--tag=gcr.io/temus-fs-chatbot/chatbot:$COMMIT_SHA"
  - "--file=./Docker/frontend.Dockerfile"
  - .
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/temus-fs-chatbot/chatbot:$COMMIT_SHA'
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'streamlit' #service name
  - '--image=gcr.io/temus-fs-chatbot/chatbot:$COMMIT_SHA'
  - "--region=us-central1"
  - "--allow-unauthenticated"
 # secretEnv: ["OPENAI_API_KEY"]
images:
- gcr.io//temus-fs-chatbot/chatbot:$COMMIT_SHA

# availableSecrets:
# secretManager:
# - versionName: projects/temus-fs-chatbot/secrets/openai_api/versions/latest
#   env: 'OPENAI_API_KEY'